// File generated by SerYL from ../llvm/utils/SerYL/examples/imports.ycd.
// Do no edit.

#include "llvm/utils/SerYL/examples/simple.h"

#include "llvm/Support/raw_ostream.h"
#include <string>
#include <stdint>
#include <vector>

namespace seryl {
namespace imported {

class Foo{
public:
  const seryl::simple::Foo &get_SimpleFoo() const {
    return _SimpleFoo;
  }
  seryl::simple::Foo &get_SimpleFoo() {
    return _SimpleFoo;
  }
private:
  seryl::simple::Foo _SimpleFoo;
public:
  void dump(llvm::raw_ostream &OS) {
  }
};


} // namespace imported
} // namespace seryl
