// File generated by SerYL from ../llvm/utils/SerYL/examples/simple.ycd.
// Do no edit.


#include "llvm/Support/raw_ostream.h"
#include <string>
#include <stdint>
#include <vector>

namespace seryl {
namespace simple {

class Foo{
public:
  int get_MyInt() const {
    return _MyInt;
  }
  void set_MyInt(int MyInt) {
    _MyInt = MyInt;
  }
private:
  int _MyInt;
public:
  const std::string &get_MyString() const {
    return _MyString;
  }
  std::string &get_MyString() {
    return _MyString;
  }
private:
  std::string _MyString;
public:
  void dump(llvm::raw_ostream &OS) {
    OS << "MyInt: " << _MyInt << "\n";
    OS << "MyString: " << _MyString << "\n";
  }
};

class Bar{
public:
  const seryl::simple::Foo &get_MyFoo() const {
    return _MyFoo;
  }
  seryl::simple::Foo &get_MyFoo() {
    return _MyFoo;
  }
private:
  seryl::simple::Foo _MyFoo;
public:
  const std::vector<double> &get_MyDoubleList() const {
    return _MyDoubleList;
  }
  std::vector<double> &get_MyDoubleList() {
    return _MyDoubleList;
  }
private:
  std::vector<double> _MyDoubleList;
public:
  void dump(llvm::raw_ostream &OS) {
    OS << "MyDoubleList:" << "\n"
    for (auto &Val : _MyDoubleList) {
      OS << "-" << Val << "\n"
    }
  }
};


} // namespace simple
} // namespace seryl
